name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python 3.10 Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - name: Install PyPi Packages
        run: pip install -r requirements-dev.txt
